apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.hostname }}
spec:
  selector:
    app: {{ .Release.Name }}-redis
  ports:
    - protocol: TCP
      port: {{ .Values.redis.port }}
      targetPort: 6379
